name: lzf_music
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.20

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  file_picker: ^10.2.0
  drift: ^2.28.0
  audio_metadata_reader:
    git:
      url: https://github.com/GerryDush/audio_metadata_reader.git
      ref: main
  path_provider: ^2.1.2
  provider: ^6.1.5
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
  window_manager: ^0.5.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  bitsdojo_window: ^0.1.6
  webdav_client: ^1.2.2
  audio_service: ^0.18.18
  audio_service_win:
     git:
      url: https://github.com/GerryDush/audio_service_win.git
      ref: main
  tray_manager: ^0.5.1
  crypto: ^3.0.0
  flutter_colorpicker: ^1.1.0
  flutter_acrylic: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.14.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/windows/icons/